version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project_manager
    ports:
      - "5432:5432"

  phppgadmin:
    image: dockage/phppgadmin
    environment:
      - PHP_PG_ADMIN_SERVER=db
      - PHP_PG_ADMIN_PORT=5432
      - PHP_PG_ADMIN_DEFAULT_DB=project_manager
      - PHP_PG_ADMIN_DEFAULT_USER=root
      - PHP_PG_ADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8888:80"
    depends_on:
      - db

  # app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgres://root:root@db:5432/project_manager_db
  #   depends_on:
  #     - db
  #   ports:
  #     - "3000:3000"
