version: "3.1"

services:
  # PostgreSQL Database
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project-manager
    networks:
      - project-manager-network

  # Admin tool for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    networks:
      - project-manager-network

  # Node.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: admin
      DB_NAME: project-manager
    depends_on:
      - db
    networks:
      - project-manager-network

networks:
  project-manager-network:

volumes:
  db_data:
