name: Deploy to Ubuntu Server with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run dev

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/tinhne/project-manager-service 
            git pull
            docker-compose down
            docker-compose up --build -d
            npx sequelize-cli db:migrate
